# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7646db079db2930e9b7db1a5c11b79e1b954d08f9fe277ddbf1a2e91c8d3b3b45dd5ca6cf69186d34f5c14e097f831035fbd1887c28e4a2a8cd01ad0ad3f6f37

test:
  secret_key_base: 574426af3e31554e6beffd49c080685e9cd0dd31c723f23ac2dce864da977f655d04945ad79398c3a4e6d1d38e2d6fad3b8250884ce797cbb6c1b0115067b2b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
